#!/bin/sh
set -e

USERNAME=${USERNAME:-user}
PASSWORD=${PASSWORD:-pass}

VOLUME=${VOLUME:-/data}
ALLOW=${ALLOW:-192.168.8.0/24 192.168.24.0/24 172.16.0.0/12 127.0.0.1/32}

mkdir -p $VOLUME

echo "$USERNAME:$PASSWORD" > /etc/rsyncd.secrets
chmod 0400 /etc/rsyncd.secrets

cat > /etc/rsyncd.conf <<EOF
port = 873
timeout = 3600
max connections = 10
transfer logging = yes

log file = /dev/stdout
pid file = /var/run/rsyncd.pid

[data]
    uid = root
    gid = root
    list = no
    hosts deny = *
    hosts allow = ${ALLOW}
    read only = false
    path = ${VOLUME}
    auth users = ${USERNAME}
    secrets file = /etc/rsyncd.secrets
EOF

exec "$@"
